version: '2'

services:
 db:
  image: mariadb
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=base_envoie_cv
 stock:
  build: .
  ports:
   - "80:80"
  links: 
   - db
  volumes:
   - .:/var/www/html
 myadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - "8080:80"
  depends_on:
   - db

 
